### ISSUE TITLE
Documentation is not up to date regarding the installation command and the latest version

### ISSUE THREAD

**Issue by ThierryAbalea** [gruntwork-io/gruntwork-installer#12]
The current one line command for the installation is working (curl -Ls https://raw.githubusercontent.com/gruntwork-io/gruntwork-installer/master/bootstrap-gruntwork-installer.sh | bash /dev/stdin --version 0.0.11)

But if you want to install the latest version (currently 0.0.16), it is not working. It seems that, starting from the 0.0.14, the version start with the letter "v". The following command is working:
curl -Ls https://raw.githubusercontent.com/gruntwork-io/gruntwork-installer/master/bootstrap-gruntwork-installer.sh | bash /dev/stdin --version v0.0.16

**Comment by brikis98** [comment]
Good catch! Fixed here: https://github.com/gruntwork-io/gruntwork-installer/commit/d3544c95f58119b7dba37acabee9ed415f0afcac
