### ISSUE TITLE
Misleading INFO log: GITHUB_OAUTH_TOKEN env var is required 

### ISSUE THREAD

**Issue by zackproser** [gruntwork-io/gruntwork-installer#53]
When calling `gruntwork-install` in a Dockerfile and attempting to download a private repo, we currently echo this INFO level log line to STDOUT: 

`2020-10-06 23:48:56 [INFO] [gruntwork-install] Repository is not public. GITHUB_OAUTH_TOKEN environment variable is required.`

In my case, given my setup, this log line was dark red - so it seemed like an error.

The first couple of times, I mistook this as meaning that `gruntwork-install` was not finding the `GITHUB_OAUTH_TOKEN` it was looking for, when in fact it's just confirming that because you're attempting to access a private repo, the token is in fact required. 

Does anyone else find this potentially confusing? If so, perhaps we should modify the messaging to be more explicit - or consider instead stating that a valid-looking `GITHUB_OAUTH_TOKEN` was found, etc.

**Comment by brikis98** [comment]
Which version? And what were you installing?

In theory, [it should only show that error if it can't publicly access the repo](https://github.com/gruntwork-io/gruntwork-installer/blob/master/gruntwork-install#L335-L338)...

**Comment by zackproser** [comment]
Sorry, this was version `v0.0.28` and I was installing the TLS scripts module from the AWS service catalogue. 

The module seemed to be installed correctly / as expected.

**Comment by zackproser** [comment]
> In theory, it should only show that error if it can't publicly access the repo...

Ah yeah, that is kind of my point though, the first couple of times I saw it it looked like an error about access, not, as it is, just a benign heads up that the tool is going to use the token to access a private repo.

Others may not find this to be an issue or as confusing as I did - but for me it's too easy to first mistake as an error stating that no `GITHUB_OAUTH_TOKEN` set.

**Comment by brikis98** [comment]
Oh, I see what you're saying. Yea, you're right, that log message should only show up if the token is required, but missing. Otherwise, it's just misleading noise.

**Comment by zackproser** [comment]
Cool - thanks for confirming. I will take care of this.

**Comment by zackproser** [comment]
To my knowledge, this remains an issue, but in order to get my GitHub notifications under control, I'm closing this out as it's 3 years old and I'm not likely to issue a PR for it anytime soon.
