### ISSUE TITLE
Improve messaging around a non-existent tag

### ISSUE THREAD

**Issue by pete0emerson** [gruntwork-io/gruntwork-installer#79]
**Describe the bug**
When installing cloud-nuke, I specified a tag that didn't exist (I omitted `v` from `v0.16.2`. The messaging was not crystal clear and led me astray:

```2022-08-01 09:44:53 [INFO] [gruntwork-install] Moving /tmp/gruntwork-script-modules/cloud-nuke_darwin_amd64 to /usr/local/bin/cloud-nuke and setting execute permissions``` 

There shouldn't be any attempt to move a non-existent binary. Even better, we might be able to detect that there was no tag specified and message that to make it really clear.

**To Reproduce**

```shell
$ gruntwork-install --binary-name 'cloud-nuke' --repo 'https://github.com/gruntwork-io/cloud-nuke' --tag '0.16.2'
2022-08-01 09:44:52 [INFO] [gruntwork-install] Installing cloud-nuke...
2022-08-01 09:44:53 [INFO] [gruntwork-install] Moving /tmp/gruntwork-script-modules/cloud-nuke_darwin_amd64 to /usr/local/bin/cloud-nuke and setting execute permissions
mv: rename /tmp/gruntwork-script-modules/cloud-nuke_darwin_amd64 to /usr/local/bin/cloud-nuke: No such file or directory
```

**Expected behavior**
Tell the user that there is no such tag.
Check to see if the binary exists before attempting to move it and message accordingly.

**Comment by denis256** [comment]
Fix included in https://github.com/gruntwork-io/fetch/releases/tag/v0.4.5
