### ISSUE TITLE
Broken module parameters parsing

### ISSUE THREAD

**Issue by mr-vercetti** [gruntwork-io/gruntwork-installer#91]
**Describe the bug**
When you want to pass module parameter that is not in the format `key=value`, but is a flag, such as `--no-cloudwatch-metrics` in this [module](https://github.com/gruntwork-io/terraform-aws-security/tree/main/modules/fail2ban), you will see an error like this:
```
2024-04-11 11:38:01 [INFO] [gruntwork-install] Executing /tmp/gruntwork-script-modules/fail2ban/install.sh --no-cloudwatch-metrics no-cloudwatch-metrics
2024-04-11 11:38:01 [ERROR] [configure-fail2ban] Unrecognized argument: no-cloudwatch-metrics
```
The script is not prepared to accept a parameter other than one that has the format `key=value`. Look [here](https://github.com/gruntwork-io/gruntwork-installer/blob/afedd68470edf544ca4cc297648076418ded3663/gruntwork-install#L313-L314).

**To Reproduce**
```
gruntwork-install --module-name 'fail2ban' --module-param 'no-cloudwatch-metrics' --repo https://github.com/gruntwork-io/module-security --tag 'v0.65.5'
```

**Expected behavior**
It should work fine with all existing parameters.

**Comment by robmorgan** [comment]
@mr-vercetti thanks for reporting this, I'll take a look this week.
